# Generated by Django 3.2.10 on 2021-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name_of_title')),
                ('task', models.TextField(max_length=200, verbose_name='Name_of_task')),
            ],
        ),
    ]
